# -*- coding: utf-8 -*-
"""TIDE_Hackathon_Day#3_End.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0i0e-m6aAuAaan06vqhuvSXPQxKD2vj
"""
import os
import pickle
import pandas as pd
import geopandas as gpd
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import osmnx as ox
import geopy.distance
import random
from shapely.geometry import Point, LineString, mapping
import json
import simpy
import geopy.distance
import json
import geopy.distance
import random
from itertools import combinations, groupby

# base directory of the whole app
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#  relative paths to the data files
railway_path = os.path.join(base_dir, 'static', 'data', 'multigraph_railway.pkl')
road_path = os.path.join(base_dir, 'static', 'data', 'multigraph.pkl')
river_path = os.path.join(base_dir, 'static', 'data', 'multigraph_river.pkl')

with open(railway_path, 'rb') as f:
    G_Rail = pickle.load(f)

with open(road_path, 'rb') as f:
    G_Road = pickle.load(f)

with open(river_path, 'rb') as f:
    G_River = pickle.load(f)


def generate_pos(function_call_input):
  function_call_input['Request Amount Land'] = 0
  function_call_input['Request Amount Rail'] = 0
  function_call_input['Request Amount River'] = 0
  function_call_input['Request Amount Air'] = 0

  if function_call_input['Object_Type'] in ['Tank','Land','Troops','Light Vehicle']:
    function_call_input['Request Amount Land'] = 1

  elif function_call_input['Object_Type'] in ['Rail','Train','Wagon']:
    function_call_input['Request Amount Rail'] = 1

  elif function_call_input['Object_Type'] in ['Boat','Ship','Barge']:
    function_call_input['Request Amount River'] = 1

  elif function_call_input['Object_Type'] in ['Jet', 'Helicopter', 'Survelliance', 'Plane']:
    function_call_input['Request Amount Air'] = 1
    
  object_positions = []
  logs = []
  list_of_list = []

  def euclidean_distance(p1, p2):
      return np.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)

  def nearest_node(x,y,G):
      # List to store distances and nodes
      distances = []
      # Iterate through each node in the graph
      for node in G.nodes(data=True):
        n1 = (node[0][0])
        n2 = (node[0][1])
        distance = euclidean_distance((x, y), (n2,n1))  # Calculate the distance
        distances.append((node, distance))  # Append node and distance as a tuple

      # Sort by distance and return the nearest node
      nearest_one = min(distances, key=lambda x: x[1])
      nearest_temp = nearest_one
      n1 = (nearest_temp[0][0][1])
      n2 = (nearest_temp[0][0][0])
      return (n2,n1)

  def move_entity(G,number_entity,env,positions,Vehicle_Type,OriginWhisperX,OriginWhisperY,DestinationWhisperX,DestinationWhisperY):
    origin = nearest_node(OriginWhisperX, OriginWhisperY,G)
    destination = nearest_node(DestinationWhisperX, DestinationWhisperY,G)
  
    shortest_path = nx.shortest_path(G, source=origin, target=destination, weight='weight')
    if function_call_input['Object_Type'] == 'Tank':
      speed = 60
    elif function_call_input['Object_Type'] == 'Light Vehicle':
      speed = 100
    elif function_call_input['Object_Type'] == 'Land':
      speed = 60
    elif function_call_input['Object_Type'] == 'Troops':
      speed = 40
    elif function_call_input['Object_Type'] in ['Rail','Train']:
      speed = 150
    elif function_call_input['Object_Type'] == 'Boat':
      speed = 40
    
    speed_m_s = speed* 1000.0 / 3600.0
    current_node = shortest_path[0]
    start_time = env.now
    
    for i in range(len(shortest_path) - 1):
      u = shortest_path[i]
      v = shortest_path[i + 1]
      distance_m = (geopy.distance.geodesic(u, v).km)*1000
    
      travel_time_s = distance_m / speed_m_s
      
      yield env.timeout(travel_time_s)
      current_node = reversed(v)
      logs.append({'time':env.now, 'positions':list(current_node),'number_entity':number_entity,'Vehicle_Type':Vehicle_Type})
      positions.append(list(current_node))

      
  def move_air_entity(env,number_entity,positions,Vehicle_Type,OXA,OYA,DXA,DYA):
    originA = [OXA,OYA]
    destinationA = [DXA, DYA]
    if Vehicle_Type == 'Jet':
      speed_m_s = 1700*1000/3600
    elif Vehicle_Type == 'Helicopter':
      speed_m_s = 350*1000/3600
    elif Vehicle_Type == 'Survelliance':
      speed_m_s = 700*1000/3600
    start_time = env.now
    distance_m = (geopy.distance.geodesic(originA, destinationA).km)*1000
    travel_time_s = distance_m / speed_m_s
    yield env.timeout(travel_time_s)
    logs.append({'time':env.now, 'positions':destinationA,'number_entity':number_entity,'Vehicle_Type':Vehicle_Type})
    positions.append(destinationA)
    yield env.timeout((travel_time_s * 1.05))
    logs.append({'time':env.now, 'positions':originA,'number_entity':number_entity,'Vehicle_Type':Vehicle_Type})

  env = simpy.Environment()
  number_of_entities_of_type = 1

  for iter_vehA in range(function_call_input['Request Amount Air']):
    env.process(move_air_entity(env,iter_vehA+1,object_positions,function_call_input['Object_Type'],function_call_input['StartLat'],function_call_input['StartLong'],function_call_input['EndLat'],function_call_input['EndLongT']))
  for iter_vehL in range(function_call_input['Request Amount Land']):
    env.process(move_entity(G_Road,iter_vehL+1,env, object_positions,function_call_input['Object_Type'],function_call_input['StartLat'],function_call_input['StartLong'],function_call_input['EndLat'],function_call_input['EndLong']))
  for iter_vehR in range(function_call_input['Request Amount Rail']):
    env.process(move_entity(G_Rail,iter_vehR+1,env, object_positions,function_call_input['Object_Type'],function_call_input['StartLat'],function_call_input['StartLong'],function_call_input['EndLat'],function_call_input['EndLong']))
  for iter_vehB in range(function_call_input['Request Amount River']):
    env.process(move_entity(G_River,iter_vehB+1,env, object_positions,function_call_input['Object_Type'],function_call_input['StartLat'],function_call_input['StartLong'],function_call_input['EndLat'],function_call_input['EndLong']))

  env.run()
  return logs

if __name__ == "__main__": 
  object_positions = []
  logs = []
  list_of_list = []

  OXT,OYT,DXT,DYT = 47.81760091349047, 4.3299753640646643, 52.03555212184733, 14.236238930682472
  coord_Tank = [OXT,OYT,DXT,DYT]
  OXR,OYR,DXR,DYR = 47.81760091349047, 4.3299753640646643, 52.03555212184733, 14.236238930682472
  coord_Rail = [OXR,OYR,DXR,DYR]
  OXB,OYB,DXB,DYB = 47.81760091349047, 4.3299753640646643, 52.03555212184733, 14.236238930682472
  coord_Boat = [OXB,OYB,DXB,DYB]
  OXA,OYA,DXA,DYA = 47.81760091349047, 4.3299753640646643, 52.03555212184733, 14.236238930682472
  coord_Jet = [OXA,OYA,DXA,DYA]
  object_type = 'Tank'

  function_call_input = {'Object_Type' : object_type,
                        'StartLat': OXT,
                        'StartLong': OYT,
                        'EndLat': DXT,
                        'EndLong': DYT,
                        }

  from pprint import pprint

  data = generate_pos(function_call_input)
  
  # print(output_dict['route'])
  # pprint(logs)
  positions = [entry['positions'] for entry in data]
  pprint(data)

  #import json
  #j_output_dict = json.dump(output_dict, open('output.json', 'w'))
  #print(output_dict)

  # import pandas as pd

